pluginManagement {
	repositories {
		gradlePluginPortal()
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'Babric'
			url = 'https://maven.glass-launcher.net/babric'
		}
		maven {
			name = 'SignalumMavenInfrastructure'
			url = 'https://maven.thesignalumproject.net/infrastructure'
		}
	}
}
